const Types = {
  SET_IMAGE_URL: 'SET_IMAGE_URL',
  SET_IMAGES: 'SET_IMAGES',
  SET_ERROR: 'SET_ERROR',
  SET_CROPPED_IMAGE_DETAILS: 'SET_CROPPED_IMAGE_DETAILS',
  SET_IMAGES_DOWNLOAD_READY: 'SET_IMAGES_DOWNLOAD_READY',
};

export default Types;
